BEGIN TRANSACTION;

DROP TABLE IF EXISTS items;


CREATE TABLE item (
	id SERIAL,
	name VARCHAR(100) NOT NULL UNIQUE,
	price NUMERIC(500) NOT NULL,
    description VARCHAR(800),
    category VARCHAR(255),
    image VARCHAR(800),
	CONSTRAINT PK_item PRIMARY KEY (id)
);

CREATE TABLE user_table (
	id SERIAL,
	username VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(500) NOT NULL
);

COMMIT TRANSACTION;
